samuelvanderwaal/metaboss

- src/parse.rs
Fixes parsing issue in #2 and compiler error on Windows builds.
> trim whitespaces from keypair ints

- src/opt.rs
- src/process_subcommands.rs
- src/update_metadata.rs
I made a few changes to the file the command is expecting. I view this as being used in conjunction with the snapshot command to get the mint accounts and therefore moved the update authority input into the arguments as opposed to the file.
> Surfacing Command for Batch Setting Update Authority

- src/decode.rs
The currently code generates JSON output like:
```
{"data":{"creators":[[{"address":"FEg3mmpcrcRsVTuc2n3oghHpRvAtEJJau4KWjaPpLKcA","share":0,"verified":true},{"address":"B5MPcaEGNF3iZH5kLjPPfhy3ieXbQ8Cgb77zSZD6gNSn","share":11,"verified":false},{"address":"uVZUoHE3W7YExtqU6cP7Vygk48noZvrMJorpuvHn1d7","share":7,"verified":false},{"address":"GR2uBCDumKagmEiGDjYsq8GjKogmbJwnfpJ14G7gxhB8","share":31,"verified":false},{"address":"GviBsqVaruw32UP6C4YMFhBffJFmoyFt65qFnJPUcgta","share":51,"verified":false}]],"name":"Galactic Gecko #5452","seller_fee_basis_points":500,"symbol":"GGSG","uri":"https://arweave.net/ULcteflMWuWWj9iCbK773xRgLhFEtwjVr8LTOy9ROoA"},"edition_nonce":255,"is_mutable":true,"key":"MetadataV1","mint":"1257AGGiM3zaYMj6LycLM1PaG8aVnk1DXHxda7X2LB2H","primary_sale_happened":true,"upda …
```
> Fix JSON encoding of `creators` field.

- src/withdraw.rs
Was just a string format issue. Stopped me from being able to build the 0.3.6 crate with `cargo install metaboss` though.
> fix build issue in withdraw.rs

- src/constants.rs
Added to respect the new rate limit of the SSC DAO RPC Endpoint.
There may be potential to modify the rate limit constants to be more specific for the SSC DAO endpoint, but this is a good start I think.
> Add SSC DAO RPC to rate limit list

- src/mint.rs
- src/opt.rs
- src/process_subcommands.rs
Just a quality of life update. Found myself having to run the sign all command quite often after minting through metaboss. Added a flag to sign each NFT as it mints instead.
> Feature sign mints

- src/opt.rs
- src/process_subcommands.rs
- src/snapshot.rs
The snapshot command now has a feature to get the holders list from a mint list file. Screenshots are attached beneath for the mint list and the corresponding holders's list
`metaboss snapshot holders -m demo-holders.json -r https://ssc-dao.genesysgo.net/`
> feat: added the feature to fetch holders when passed a mint list file

- src/opt.rs
- src/process_subcommands.rs
- src/sign.rs
- src/snapshot.rs
- src/update_metadata.rs
This feature makes sure users can snapshot a creator within any index of the creator's array. Also makes sure to not exceed the index by 4.
1. Snapshot mints
2. Snapshot holders
> feat: updated snapshot command to support creator position

- src/main.rs
Looks like this part of the code which removes the trailing / is breaking quick node RPC as looks like quick node relies on the trailing / for their RPC to work. This PR reverts it back.
> Fix quick node RPC 404 not found issue

- src/opt.rs
- src/process_subcommands.rs
- src/update_metadata.rs
Hey!
In some cases it can happen that it is not possible to send funds to the update authority even though one has access to it. (Current example: A project with a rogue dev that is transferring all funds out of the authority wallet all the time. For this project it's not possible to change the update authority, metadata etc.)
The change here allows to add a --keypair-payer option and use another wallet to pay the transaction.
```
./metaboss set update-authority-all --keypair updateAuthority.json --mint-accounts-file nfts.json --new-update-authority <public key> -p keypairPayer.json
```
If no payer is provided the keypair option would be used as payer (or if that is not provided the solana config).
Tested in devnet and mainnet already.
Regards!
> allow use of different payer for set update-authority

- Cargo.lock
- Cargo.toml
- src/collections/items.rs
- src/collections/methods.rs
- src/collections/migrate.rs
- src/constants.rs
- src/create/methods.rs
- src/create/mod.rs
- src/lib.rs
- src/main.rs
- src/opt.rs
- src/process_subcommands.rs
Adds the `create` subcommand with:
* `create metadata` for decorating an existing SPL mint with a Metaplex metadata account
* `create fungible` for creating a new SPL token and metadata account
> feat: add create metadata & fungible commands

- src/parse.rs
Creator can be `None` but metaboss does not allow that
`metaboss mint one --nft-data-file nft-sample.json`
```
{
"name": "The NFT with no creatore",
"symbol": "",
"uri": "https://arweave.net/FPGAv1XnyZidnqquOdEbSY6_ES735ckcDTdaAtI7GFw",
"seller_fee_basis_points": 0
}
```
> feat: Allow None creator

- scripts/install.sh
Added RELEASE_URL and RELEASE variables.
Display REMOTE_URL before downloading.
Added -f flag in curl command to catch errors.
> added -f flag to catch curl failures

- src/collections/migrate.rs
- src/derive.rs
- src/opt.rs
- src/process_subcommands.rs
- src/sign.rs
- src/snapshot/data.rs
- src/snapshot/methods.rs
Currently the snapshot and sign commands only support candy machine v1 and v2. This PR adds the possibility to use a --v3 flag to derive it correctly.
> allow --v3 snapshot and signing

- src/collections/data.rs
- src/theindexio/data.rs
I noticed this issue after trying to fetch collection items using metaboss:
```bash
❯ metaboss collections get-items --collection-mint 9jnJWH9F9t1xAgw5RGwswVKY4GvY2RXhzLSJgpBAhoaR --api-key some-indexio-api-key
[=   ] Fetching data from TheIndex.io. . .
Error: error decoding response body: unknown variant `NonFungibleEdition`, expected one of `NonFungible`, `Fungible`, `FungibleAsset`, `NonfungibleEdition` at line 1 column 5002805
Caused by:
unknown variant `NonFungibleEdition`, expected one of `NonFungible`, `Fungible`, `FungibleAsset`, `NonfungibleEdition` at line 1 column 5002805
```
> fix: typo in TokenStandard struct

- src/collections/methods.rs
Merge after Token Metadata fix is deployed to mainnet.
> use safe_deserialize; allow unverifying w/ burned parent

- Cargo.lock
- Cargo.toml
- src/collections/migrate.rs
- src/opt.rs
- src/process_subcommands.rs
- src/transfer/mod.rs
- src/update/creator.rs
- src/update/data.rs
- src/update/immutable.rs
- src/update/name.rs
- src/update/primary_sale_happened.rs
- src/update/rule_set.rs
- src/update/seller_fee_basis_points.rs
- src/update/symbol.rs
- src/update/update_authority.rs
- src/update/uri.rs
- src/update/uses.rs
This PR adds an option to specify a receiver account on `transfer`. This allows transferring assets to a token (non-ATA) account.
> Add receiver account transfer option

- docs-src/src/set.md
- docs-src/src/update.md
--mint-list and -n was outdated
> fix commands

- Cargo.lock
- Cargo.toml
- src/create/methods.rs
- src/main.rs
- src/mint.rs
- src/opt.rs
- src/process_subcommands.rs
User can now specify a keypair file to be used as the mint to allow creating NFTs and fungible tokens with vanity mint addresses.
> allow vanity mints for single mint commands

- src/mint.rs
- src/opt.rs
- src/process_subcommands.rs
Support added for fungible token minting. The following screenshot represents the structure of the command. 
The amount doesn't need to take account of decimals as the calculation is done inside the processor function.
> feat: added command for minting fungible tokens

- src/derive.rs
- src/opt.rs
- src/process_subcommands.rs
Created a `derive` subcommand named `token-account` which also supports the token extensions program.
1. Command help page
2. Deriving for token keg program ID
3. Deriving for token extensions program ID
> feat: implement derive token account functionality

- docs-src/src/priority_fees.md
- docs-src/src/snapshot.md
- src/opt.rs
fix some typos and link broken
> chore: fix typos and link broken

- src/create/methods.rs
Probably due to https://github.com/metaplex-foundation/mpl-token-metadata/issues/140
> Fix: `error processing instruction 0: 0x95` for `create-fungible`

- .github/workflows/build.yml
GitHub runners now only offer intel runners for `macos-latest-large` images:
([source](https://github.com/actions/runner-images/blob/6cc2576b1b19c08317047523d5abe3c48a9eab98/README.md#available-images))
| Image | YAML Label |
| ------- |--------------|
| macOS 15 <sup>beta</sup> | `macos-15-large` |
| macOS 15 Arm64 <sup>beta</sup> | `macos-15` or `macos-15-xlarge` |
| macOS 14 | `macos-latest-large` or `macos-14-large` |
| macOS 14 Arm64 |`macos-latest`, `macos-14`, `macos-latest-xlarge` or `macos-14-xlarge` |
fixes #359
> fix: MacOS arch in CI
